language: ruby
sudo: false
dist: xenial
rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install bundler
  - bundle

services:
  - postgresql

env:
  - DATABASE_USERNAME=postgres
  - DATABASE_PASSWORD=
  - DATABASE_HOST=127.0.0.1
  - DATABASE_PORT=5432

script:
  - rails db:setup
  - rspec

branches:
  only:
    - master

cache:
  directories:
  - .autoconf
