language: ruby
sudo: false
dist: xenial
rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install bundler
  - bundle

before_script:
  - pip install --user codecov

services:
  - postgresql

env:
  - DATABASE_USERNAME=postgres DATABASE_PASSWORD= DATABASE_HOST=127.0.0.1 DATABASE_PORT=5432

script:
  - rails db:setup
  - rspec

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

cache:
  directories:
  - .autoconf

deploy:
  provider: heroku
  api_key:
    secure: "gw9Tuwq0gjwECv+u3ejAWQRRQL7XgZjFjok7LMSKKWbhdwg82KH/8ZR4b1N1ZRDgGmuI/6FUMaBbJaJ+T7arzIpLPMPxGDmCF5iSsd/qn8LxC654iuGtcrYJmHE/19itGeFATk7sq6JkXAljnhwqfBxPul1FizWWe/XWzpz3wpJsK2pI31lNueEcGtuQQvd5STxWB9oZ7/fQMbcuiKSglgJkLB42rQVPJW7Lr3SszoraPMe3r/dWusEkJLkeFpTXNIXBTXtLoU16F8EB08bF4ruzxogHulI1+5rETFogzPpeyyvkTnGpiySo2SPNVBIGR4sLd1iVxSpWC21XsAL6aUrD32LTyc/kqvCrgg5YYPKkUpTe4RDewVE8ZUy9CgECb2ELXNIFEVODgvR4zrcHVkRLCz2CDGfudw2tsVH23L7tgrYHcyUJB3NvUXDkDq+hpRuHOzimcR2R1xnsE9kEzojUG9sbSOLMfiexuzjtICsnHEtILUpPv245fLR7i9qt9jd3DJMXT39SEmzGvwEYnlkuUvs5CbKjnKVCN5rWGUIlm0xK77gJCR+f8fWtiWdJv7qDJFFlzeSn9afJDQerTAjQVB1MnKsLR3sUdLG+2b8j/0dgcUDA5ctjAdCwKNYSoNo76d+SrosvASmzjbBZ+ifjAHZmG5qIA4DmtaYRm0A="
  # run commands after successful deploy to Heroku
  run:
    - "sleep 30"
    - "pwd"
    - "ls -lsh"
    - "rake db:migrate"
    - "rake db:reseed"
  app: simple-rblog
  on:
    repo: mkdika/rblog

notifications:
  email:
    recipients:
      - mkdika@gmail.com
    on_success: always
    on_failure: always